class API {
  // static String baseUrl = "https://192.168.29.125/flutter-app";
  // static String baseUrl = "https://wp.workdo.io/gostore-flutter";
  // static String consumerKey = 'ck_94cd1a3793de218f56abe030541682035ee96683';
  // static String consumerSecret = 'cs_35e3894d3a9ef45594179e94d7ab003ece8687c3';
  static String consumerKey = 'ck_283dba1446126767c72c379e23049c21e210b77e';
  static String coCartUrl = '/wp-json/cocart/v2/';
  static String baseUrl = "https://www.ahmad-saadeddin.com";
  static String consumerSecret = 'cs_cc5cc50a02265ff496784ea5c620f95d47683ea1';
  static String wcUrl = '/wp-json/wc/v3/';
  static String authUrl = '/wp-json/api-bearer-auth/v1/';
  static String loginUrl = 'login';
  static String customersUrl = 'customers';
  static String forgetPasswordUrl = '/wp-json/forget-password/send-code';
  static String verifyOtpUrl = '/wp-json/forget-password/verify-code';
  static String updatePasswordUrl = '/wp-json/forget-password/update-password';
  static String productsUrl = 'products';
  static String categoriesUrl = '/categories';
  static String categoryUrl = '?category=';
  static String reviewsUrl = '/reviews';
  static String cartUrl = 'cart';
  static String addItemUrl = '/add-item';
  static String itemUrl = '/item/';
  static String onSaleUrl = '/?on_sale=';
  static String searchUrl = '/?search=';
  static String blogUrl = '/wp-json/wp/v2/posts';
  static String perPageUrl = '?per_page=';
  static String productKeyUrl = "?product=";
  static String orderByUrl = "/?orderby=";
  static String parentUrl = "?parent=";
  static String includeUrl = "?include=";
  static String tagUrl = "/tags";
  static String attributesUrl = "/attributes";
  static String termsUrl = "/terms";
  static String featuredUrl = "/?featured=";
  static String afterUrl = "/?after=";
  static String beforeUrl = "&before=";
  static String ordersUrl = "orders";
  static String clearUrl = "/clear";
  static String imageUrl = "/wp-json/wp/v2/media";
  static String applyCouponUrl = "coupon/apply-coupon";
  static String userIdUrl = "?user_id=";
  static String userAddressUrl = "/wp-json/user-address/";
  static String saveAddressUrl = "add-address";
  static String listAddressUrl = "list-address";
  static String bestSellersUrl = "/wp-json/home/best-sellers";
}
